config/routes.rb
Rails.application.routes.draw do
  get 'company_users/index'
  resources :companies
  devise_for :users, controllers: {
          sessions: 'users/sessions',
          passwords: 'users/passwords',
          registrations: 'users/registrations'
        }
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  after_action :assign_user_role, only: [:create]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    @company.user_id = current_user.id

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
      authorize @company
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:user_id, :name)
      
    end
    
    def assign_user_role
      # Rails.logger.info "New company created with ID: #{@company.id}"
      role = Role.find_by(name: 'admin')
      # Rails.logger.info "Admin role found with ID: #{role.id}"
      assignment = Assignment.new(company_id: @company.id, role_id: role.id, user_id: current_user.id)
      begin
        assignment.save
      rescue
        Rails.logger.info "Can not save assignment"
      end
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<div class="col-lg-6 card mt-3">
	<div class="card-body">
		<%= form_with(model: company, local: true) do |form| %>
		  <% if company.errors.any? %>
		    <div id="error_explanation">
		      <p><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</p>

		      <ul>
		      <% company.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		      </ul>
		    </div>
		  <% end %>

		  <div class="form-group">
		    <%= form.label :name %>
		    <%= form.text_field :name, class: "form-control" %>
		  </div>

		  <div class="form-group">
		    <%= form.submit 'Submit', class: "btn btn-sm btn-success" %>
		  </div>
		<% end %>
		
	</div>
</div>

app/views/companies/edit.html.erb
<%= render 'form', company: @company %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.user %></td>
        <td><%= company.name %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<%= render 'form', company: @company %>

app/views/companies/show.html.erb
<div class="col-lg-6 card mt-3">
	<div class="card-body">
		<p>
		  <strong>User:</strong>
		  <%= @company.user.email %>
		</p>

		<p>
		  <strong>Name:</strong>
		  <%= @company.name %>
		</p>

		<%= link_to 'Edit', edit_company_path(@company) %> |
		<%= link_to 'Back', root_path %>
		
	</div>
</div>